apiVersion: v1
kind: Service
metadata:
  name: grafana-frontend
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/instance: grafana
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 3000
  type: LoadBalancer
