apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-2
  template:
    metadata:
      labels:
        app: iot-sensor-2
    spec:
      containers:
        - name: iot-sensor-2
          image: wpatterson134/iot-sensor:latest
          env:
            - name: sensor.id
              valueFrom:
                configMapKeyRef:
                  name: sensor-config
                  key: IOT_SENSOR_2_ID
            - name: sensor.name
              valueFrom:
                configMapKeyRef:
                  name: sensor-config
                  key: IOT_SENSOR_2_NAME
            - name: sensor.place.id
              valueFrom:
                configMapKeyRef:
                  name: sensor-config
                  key: IOT_SENSOR_2_PLACE_ID
