apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          hostname: kafka-exporter
          image: bitnami/kafka-exporter:latest
          args:
            - '--kafka.server=kafka:9092'
            - '--web.listen-address=0.0.0.0:9308'  # Listening on all interfaces inside the container
            - '--web.telemetry-path=/metrics'
            - '--log.level=debug'
          ports:
            - containerPort: 9308
          restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
    - protocol: TCP
      port: 9308    # Service port
      targetPort: 9308  # Container's port
  type: ClusterIP  # Internal access within the cluster
