apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8084  # External access
      targetPort: 8081  # Container port
  type: LoadBalancer  
