# Eclipse Mosquitto is an open source (EPL/EDL licensed) message broker that implements the 
# MQTT protocol versions 5.0, 3.1.1 and 3.1. Mosquitto is lightweight and is suitable for use on all devices from 
# low power single board computers to full servers.
# The MQTT protocol provides a lightweight method of carrying out messaging using a publish/subscribe model. 
# This makes it suitable for Internet of Things messaging such as with low power sensors or mobile devices such 
# as phones, embedded computers or microcontrollers.
# The Mosquitto project also provides a C library for implementing MQTT clients, and the 
# very popular mosquitto_pub and mosquitto_sub command line MQTT clients.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config-volume
          configMap:
            name: mosquitto-config

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883  # The service port exposed within the cluster
      targetPort: 1883  # The container port in the pod
  type: ClusterIP  # Internal communication within the cluster


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
