apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v0.8.0
      ports:
        containerPort: 9091
      restartPolicy: Always