apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoonavigator-web-deployment
  labels:
    app: zoonavigator-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoonavigator-web
  template:
    metadata:
      labels:
        app: zoonavigator-web
    spec:
      containers:
      - name: zoonavigator-web
        image: elkozmon/zoonavigator-web:latest
        ports:
        - containerPort: 8000
        env:
        # The following two keys instruct the web component how to connect to
      # the backing api component.
          - name: API_HOST
            value: "9000"
        limits:
          cpu:
          memory:
          #TODO: add mem and cpu limits

        #Zoonavigator relies on zoonavigator-web
    # This will instruct docker to wait until those services are up
    # before attempting to start zoonavigator-web.
    # depends_on:
    #   - zoonavigator-api

--- 
apiVersion: v1
kind: Service
metadata:
  name: zoonavigator-web-service
spec:
  selector:
    app: zoonavigator-web
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8000
  type: ClusterIP
