apiVersion: v1
kind: Service
metadata:
  name: my-bridge-bridge-service
spec:
  selector:
    strimzi.io/kind: KafkaBridge
    strimzi.io/cluster: my-bridge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
